version: "3.3"

services:
  app:
    build: .
    container_name: urlShortener
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: urlshortener
      DB_PORT: 5432
    depends_on:
      - db

  db:
    restart: always
    image: postgres:15.2
    container_name: urlShortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  postgres_data:
