version: '3.8'

services:
  app:
    build: .
    container_name: urlShortener
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: urlshortener
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: urlShortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: urlshortener
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: